# Site settings
title: "On Integrated Circuits Design, Life and Philosophy"
author: "Zhikai"
description: "This is a blog about IC Design(my major), some life stories(my joy), and the occasional philosophy(my persuit). Not necessarily in that order."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am a senior student from Xi'an Jiaotong University(XJTU), major in IC design. "
colophon: "© GyanStar - Since 2015<br>Contact me via icecrystals@163.com."

baseurl: ""
url: "http://hugosereno.eu"

twitter_username: Gyan_Star
github_username: cnzhikai
zhihu: GyanStar
#linkedin_username: Zhikai Huang
#facebook_username: Zhikai Huang
#google-analytics: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
